services:
  postgres:
    image: postgres:17
    container_name: login_demo_db
    environment:
      POSTGRES_DB: login_demo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123Login
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
